{% set name = "omero-server-setup" %}
{% set version = "0.0.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}{{ environ.get('VERSION_SUFFIX', '') }}"

source:
  git_url: https://github.com/manics/omero-server-setup.git
  git_rev: {{ version }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  script_env:
    - VERSION_SUFFIX

requirements:
  host:
    - pip
    - python =3
    - setuptools_scm
  run:
    - python =3
    - omero-py-minimal >=5.6

test:
  commands:
    - omero setup --help
    - omero setup createconfig --help
    - omero setup justdoit --help
    - omero setup create --help
    - omero setup init --help
    - omero setup upgrade --help
    - omero setup dump --help
    - omero setup certificates --help
    - omero setup pginit --help
    - omero setup pgstart --help
    - omero setup pgstop --help
    - omero setup start --help
    - omero setup stop --help
  imports:
    - omero_server_setup
    - omero_server_setup.certificates
    - omero_server_setup.cli
    - omero_server_setup.createconfig
    - omero_server_setup.db
    - omero_server_setup.external

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: OMERO server setup and database management plugin
  doc_url: https://github.com/manics/omero-server-setup
  dev_url: https://github.com/manics/omero-server-setup

extra:
  recipe-maintainers:
    - ome
